### ISSUE TITLE
如果把prompt定义成可学习的参数，针对不同退化类型的数据训练完成后，当对某张退化图像重建推理时，是否需要人为指定(输入）这个prompt？

### ISSUE THREAD

**Issue by Note-Liu** [leonmakise/ProRes#5]
推理时，prompt是需要人为指定/输入的吗？

**Comment by leonmakise** [comment]
感谢关注我们的工作！

推理时是需要用户按照自身需求指定prompt的输入，而退化类型可以在使用前观察到。
这样针对某张图像中存在的多种退化类型，用户可以自定义复原的退化，从而保留希望存在的退化，满足用户需求，实现操纵性。

**Comment by Note-Liu** [comment]
> 感谢关注我们的工作！
> 
> 推理时是需要用户按照自身需求指定prompt的输入，而退化类型可以在使用前观察到。 这样针对某张图像中存在的多种退化类型，用户可以自定义复原的退化，从而保留希望存在的退化，满足用户需求，实现操纵性。

感谢解答！
